input {
  beats {
    id => "application-beats-input"
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "adr-manager-logs-%{+YYYY.MM.dd}"
  }
}
