import { yupResolver } from '@hookform/resolvers/yup';
import { Alert, Box, Button, CircularProgress, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Controller, useForm } from 'react-hook-form';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import * as yup from 'yup';
import { useAuth } from '../auth/AuthProvider';
import { adrApi, type AdrInput } from './adrApi';
import { AuditHistory } from '../audit/AuditHistory';
import { ContentSection, EmptyState, PageHeader, StatusChip, WorkspaceBreadcrumbs } from '../workspace/Workspace';

const schema: yup.ObjectSchema<AdrInput> = yup.object({ title: yup.string().trim().required('Title is required').max(255), context: yup.string().trim().required('Context is required'), problem: yup.string().trim().required('Problem is required'), optionsConsidered: yup.string().optional(), decision: yup.string().optional(), consequences: yup.string().optional(), version: yup.number().optional() });
const message = (error: unknown) => error instanceof Error ? error.message : 'The ADR request could not be completed.';

export function AdrsPage() {
  const { adlIdentifier = '' } = useParams(); const { user } = useAuth(); const token = user?.access_token ?? '';
  const adrs = useQuery({ queryKey: ['adrs', adlIdentifier], queryFn: () => adrApi.list(token, adlIdentifier), enabled: Boolean(token && adlIdentifier) });
  return <Stack spacing={3}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs', to: '/adls' }, { label: adlIdentifier, to: `/adls/${adlIdentifier}` }, { label: 'Architecture Decision Records' }]}/><PageHeader eyebrow="Decision log" title="Architecture Decision Records" description="Record decisions in one shared decision context." action={<Button component={Link} to={`/adls/${adlIdentifier}/adrs/new`} variant="contained">Create ADR</Button>}/>
    {adrs.error && <Alert severity="error">{message(adrs.error)}</Alert>}<ContentSection title="Architecture Decision Records">{adrs.isLoading ? <Box display="flex" justifyContent="center" py={4}><CircularProgress aria-label="Loading ADRs"/></Box> : adrs.data?.length === 0 ? <EmptyState title="No Architecture Decision Records yet" description="Create an ADR to record the first decision for this ADL." action={<Button component={Link} to={`/adls/${adlIdentifier}/adrs/new`} variant="contained">Create ADR</Button>}/> : <Box sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Identifier</TableCell><TableCell>Title</TableCell><TableCell>Status</TableCell><TableCell>Author</TableCell></TableRow></TableHead><TableBody>{adrs.data?.map((adr) => <TableRow component={Link} to={`/adrs/${adr.identifier}`} hover key={adr.identifier} sx={{ textDecoration: 'none' }}><TableCell>{adr.identifier}</TableCell><TableCell>{adr.title}</TableCell><TableCell><StatusChip status={adr.status}/></TableCell><TableCell>{adr.authorDisplayName}</TableCell></TableRow>)}</TableBody></Table></Box>}</ContentSection></Stack>;
}

export function AdrFormPage() {
  const { adlIdentifier, identifier } = useParams(); const { user } = useAuth(); const token = user?.access_token ?? ''; const navigate = useNavigate(); const queryClient = useQueryClient();
  const detail = useQuery({ queryKey: ['adr', identifier], queryFn: () => adrApi.detail(token, identifier!), enabled: Boolean(token && identifier) });
  const form = useForm<AdrInput>({ resolver: yupResolver(schema), values: detail.data ? { title: detail.data.title, context: detail.data.context, problem: detail.data.problem, optionsConsidered: detail.data.optionsConsidered ?? '', decision: detail.data.decision ?? '', consequences: detail.data.consequences ?? '', version: detail.data.version } : { title: '', context: '', problem: '', optionsConsidered: '', decision: '', consequences: '' } });
  const save = useMutation({ mutationFn: (value: AdrInput) => identifier ? adrApi.update(token, identifier, value) : adrApi.create(token, adlIdentifier!, value), onSuccess: (adr) => { void queryClient.invalidateQueries({ queryKey: ['adrs', adr.adlIdentifier] }); void queryClient.invalidateQueries({ queryKey: ['adr', adr.identifier] }); navigate(`/adrs/${adr.identifier}`); } });
  if (identifier && detail.isLoading) return <CircularProgress aria-label="Loading ADR"/>;
  if (identifier && detail.data && detail.data.status !== 'DRAFT') return <AdrDetailPage />;
  const parent = adlIdentifier ?? detail.data?.adlIdentifier;
  return <Stack component="form" spacing={3} onSubmit={form.handleSubmit((value) => save.mutate(value))}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs', to: '/adls' }, ...(parent ? [{ label: parent, to: `/adls/${parent}` }] : []), ...(identifier ? [{ label: identifier, to: `/adrs/${identifier}` }] : []), { label: identifier ? 'Edit ADR' : 'Create ADR' }]}/><PageHeader eyebrow="Architecture Decision Record" title={identifier ? 'Edit ADR' : 'Create ADR'} description="Document the decision so it is easy to revisit."/>{save.error && <Alert severity="error">{message(save.error)}</Alert>}<ContentSection title="Architecture Decision Record"><Stack spacing={2}><AdrFields form={form}/></Stack></ContentSection><Button type="submit" variant="contained" disabled={save.isPending} sx={{ alignSelf: 'flex-start' }}>{save.isPending ? 'Saving…' : 'Save ADR'}</Button></Stack>;
}

function AdrFields({ form }: { form: ReturnType<typeof useForm<AdrInput>> }) { return <><Controller control={form.control} name="title" render={({ field, fieldState }) => <TextField {...field} label="Title" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="context" render={({ field, fieldState }) => <TextField {...field} multiline minRows={3} label="Context" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="problem" render={({ field, fieldState }) => <TextField {...field} multiline minRows={3} label="Problem" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="optionsConsidered" render={({ field }) => <TextField {...field} multiline minRows={2} label="Options considered"/>}/><Controller control={form.control} name="decision" render={({ field }) => <TextField {...field} multiline minRows={2} label="Decision"/>}/><Controller control={form.control} name="consequences" render={({ field }) => <TextField {...field} multiline minRows={2} label="Consequences"/>}/></>; }

export function AdrDetailPage() {
  const { identifier } = useParams(); const { user } = useAuth(); const token = user?.access_token ?? ''; const queryClient = useQueryClient();
  const [comment, setComment] = useState(''); const [rejectionJustification, setRejectionJustification] = useState('');
  const detail = useQuery({ queryKey: ['adr', identifier], queryFn: () => adrApi.detail(token, identifier!), enabled: Boolean(token && identifier) });
  const action = useMutation({ mutationFn: ({ kind, adr }: { kind: 'submit' | 'cancel' | 'approve' | 'reject'; adr: { identifier: string; version: number } }) => {
    if (kind === 'submit') return adrApi.submit(token, adr.identifier, adr.version);
    if (kind === 'cancel') return adrApi.cancelReview(token, adr.identifier, adr.version);
    if (kind === 'approve') return adrApi.approve(token, adr.identifier, adr.version, comment);
    return adrApi.reject(token, adr.identifier, adr.version, comment, rejectionJustification);
  }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['adr', identifier] }); void queryClient.invalidateQueries({ queryKey: ['audit', 'adr', identifier] }); } });
  if (detail.isLoading) return <CircularProgress aria-label="Loading ADR"/>; if (detail.error) return <Alert severity="error">{message(detail.error)}</Alert>; const adr = detail.data!;
  return <Stack spacing={3}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs', to: '/adls' }, { label: adr.adlIdentifier, to: `/adls/${adr.adlIdentifier}` }, { label: adr.title }]}/><PageHeader eyebrow="Architecture Decision Record" title={adr.title} action={<StatusChip status={adr.status}/>}/>{action.error && <Alert severity="error">{message(action.error)}</Alert>}<ContentSection title="Decision context"><Stack spacing={1.5}><Typography><strong>Identifier:</strong> {adr.identifier}</Typography><Typography><strong>Author:</strong> {adr.authorDisplayName}</Typography><Typography><strong>Context:</strong> {adr.context}</Typography><Typography><strong>Problem:</strong> {adr.problem}</Typography></Stack></ContentSection><ContentSection title="Decision and outcome"><Stack spacing={1.5}><Typography><strong>Options considered:</strong> {adr.optionsConsidered || 'None'}</Typography><Typography><strong>Decision:</strong> {adr.decision || 'Not decided'}</Typography><Typography><strong>Consequences:</strong> {adr.consequences || 'None'}</Typography>{adr.decidedByDisplayName && <Typography><strong>Decided by:</strong> {adr.decidedByDisplayName} at {adr.decidedAt ? new Date(adr.decidedAt).toLocaleString() : ''}</Typography>}{adr.decisionComment && <Typography><strong>Decision comment:</strong> {adr.decisionComment}</Typography>}{adr.rejectionJustification && <Typography><strong>Rejection justification:</strong> {adr.rejectionJustification}</Typography>}</Stack></ContentSection>{adr.status === 'UNDER_REVIEW' && <ContentSection title="Review decision"><Stack spacing={2}><TextField label="Decision comment" value={comment} onChange={(event) => setComment(event.target.value)}/><TextField required label="Rejection justification" value={rejectionJustification} onChange={(event) => setRejectionJustification(event.target.value)}/><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button variant="contained" onClick={() => action.mutate({ kind: 'approve', adr })} disabled={action.isPending}>Approve</Button><Button color="warning" onClick={() => action.mutate({ kind: 'reject', adr })} disabled={action.isPending || !rejectionJustification.trim()}>Reject</Button>{user?.profile.sub === adr.authorUserId && <Button onClick={() => action.mutate({ kind: 'cancel', adr })} disabled={action.isPending}>Cancel review</Button>}</Stack></Stack></ContentSection>}<Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}>{adr.status === 'DRAFT' && <><Button component={Link} to={`/adrs/${adr.identifier}/edit`}>Edit ADR</Button><Button variant="contained" onClick={() => action.mutate({ kind: 'submit', adr })} disabled={action.isPending}>Submit for review</Button></>}</Stack>{adr.status !== 'DRAFT' && <Alert severity="info">This ADR is read-only in its {adr.status} state.</Alert>}<AuditHistory kind="adr" identifier={adr.identifier}/></Stack>;
}
