import { yupResolver } from '@hookform/resolvers/yup';
import { Alert, Box, Button, CircularProgress, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import * as yup from 'yup';
import { useAuth } from '../auth/AuthProvider';
import { adlApi, type AdlInput } from './adlApi';
import { AuditHistory } from '../audit/AuditHistory';
import { ContentSection, EmptyState, PageHeader, StatusChip, WorkspaceBreadcrumbs } from '../workspace/Workspace';

const schema: yup.ObjectSchema<AdlInput> = yup.object({ title: yup.string().trim().required('Title is required').max(255), context: yup.string().trim().required('Context is required'), problem: yup.string().trim().required('Problem is required'), tags: yup.array(yup.string().trim().max(64).required()).required(), version: yup.number().optional() });
const message = (error: unknown) => error instanceof Error ? error.message : 'The ADL request could not be completed.';

export function AdlsPage() {
  const { user } = useAuth(); const [filters, setFilters] = useState({ text: '' }); const token = user?.access_token ?? '';
  const adls = useQuery({ queryKey: ['adls', filters], queryFn: () => adlApi.list(token, Object.fromEntries(Object.entries(filters).filter(([, v]) => v))), enabled: Boolean(token) });
  return <Stack spacing={3}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs' }]}/><PageHeader eyebrow="Decision register" title="Architecture Decision Logs" description="Keep context, decisions, and outcomes together." action={<Button component={Link} to="/adls/new" variant="contained">Create ADL</Button>}/>
    <ContentSection title="Browse logs"><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="Search decision logs" value={filters.text} onChange={(e) => setFilters({ ...filters, text: e.target.value })}/></Stack>
    {adls.error && <Alert severity="error">{message(adls.error)}</Alert>}{adls.isLoading ? <Box display="flex" justifyContent="center" py={4}><CircularProgress aria-label="Loading ADLs"/></Box> : adls.data?.content.length === 0 ? <EmptyState title="No matching decision logs" description="Try another search, or create an ADL to start a new conversation." action={<Button component={Link} to="/adls/new" variant="contained">Create ADL</Button>}/> : <Box sx={{ overflowX: 'auto' }}><Table><TableHead><TableRow><TableCell>Identifier</TableCell><TableCell>Title</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{adls.data?.content.map((adl) => <TableRow component={Link} to={`/adls/${adl.identifier}`} hover key={adl.identifier} sx={{ textDecoration: 'none' }}><TableCell>{adl.identifier}</TableCell><TableCell>{adl.title}</TableCell><TableCell>{adl.archivedAt ? 'ARCHIVED' : 'ACTIVE'}</TableCell></TableRow>)}</TableBody></Table></Box>}</ContentSection></Stack>;
}

export function AdlFormPage() {
  const { identifier } = useParams(); const { user } = useAuth(); const token = user?.access_token ?? ''; const queryClient = useQueryClient(); const navigate = useNavigate(); const [feedback, setFeedback] = useState<string | null>(null);
  const detail = useQuery({ queryKey: ['adl', identifier], queryFn: () => adlApi.detail(token, identifier!), enabled: Boolean(identifier && token) });
  const form = useForm<AdlInput>({ resolver: yupResolver(schema), values: detail.data ? { title: detail.data.title, context: detail.data.context, problem: detail.data.problem, tags: detail.data.tags, version: detail.data.version } : { title: '', context: '', problem: '', tags: [] } });
  const save = useMutation({ mutationFn: (value: AdlInput) => identifier ? adlApi.update(token, identifier, value) : adlApi.create(token, value), onSuccess: (adl) => { void queryClient.invalidateQueries({ queryKey: ['adls'] }); void queryClient.invalidateQueries({ queryKey: ['adl', adl.identifier] }); navigate(`/adls/${adl.identifier}`); } });
  if (identifier && detail.isLoading) return <CircularProgress aria-label="Loading ADL"/>;
  if (identifier && detail.data?.archivedAt) return <AdlDetailPage />;
  return <Stack component="form" spacing={3} onSubmit={form.handleSubmit((value) => { setFeedback(null); save.mutate({ ...value, tags: value.tags.filter(Boolean) }); })}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs', to: '/adls' }, ...(identifier ? [{ label: identifier, to: `/adls/${identifier}` }] : []), { label: identifier ? 'Edit ADL' : 'Create ADL' }]}/><PageHeader eyebrow="Decision log" title={identifier ? 'Edit ADL' : 'Create ADL'} description="Give this decision a shared context before it is documented."/>{(feedback || save.error) && <Alert severity="error">{feedback ?? message(save.error)}</Alert>}<ContentSection title="Decision context"><Stack spacing={2}><Controller control={form.control} name="title" render={({field,fieldState}) => <TextField {...field} label="Title" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="context" render={({field,fieldState}) => <TextField {...field} multiline minRows={3} label="Context" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="problem" render={({field,fieldState}) => <TextField {...field} multiline minRows={3} label="Problem" error={Boolean(fieldState.error)} helperText={fieldState.error?.message}/>}/><Controller control={form.control} name="tags" render={({field}) => <TextField label="Tags (comma separated)" value={field.value.join(', ')} onChange={(e) => field.onChange(e.target.value.split(',').map((tag) => tag.trim()))}/>}/></Stack></ContentSection><Button type="submit" variant="contained" disabled={save.isPending} sx={{ alignSelf: 'flex-start' }}>{save.isPending ? 'Saving…' : 'Save ADL'}</Button></Stack>;
}

export function AdlDetailPage() {
  const { identifier } = useParams(); const { user } = useAuth(); const token = user?.access_token ?? ''; const queryClient = useQueryClient(); const navigate = useNavigate(); const detail = useQuery({ queryKey: ['adl', identifier], queryFn: () => adlApi.detail(token, identifier!), enabled: Boolean(identifier && token) }); const archive = useMutation({ mutationFn: () => adlApi.archive(token, identifier!, detail.data!.version), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['adl', identifier] }); void queryClient.invalidateQueries({ queryKey: ['adls'] }); } });
  if (detail.isLoading) return <CircularProgress aria-label="Loading ADL"/>; if (detail.error) return <Alert severity="error">{message(detail.error)}</Alert>; const adl = detail.data!;
  const archived = Boolean(adl.archivedAt);
  return <Stack spacing={3}><WorkspaceBreadcrumbs items={[{ label: 'Decision Logs', to: '/adls' }, { label: adl.title }]}/><PageHeader eyebrow="Decision log" title={adl.title} action={<StatusChip status={archived ? 'ARCHIVED' : 'ACTIVE'}/>}/>{archive.error && <Alert severity="error">{message(archive.error)}</Alert>}<ContentSection title="Overview"><Stack spacing={1.5}><Typography><strong>Identifier:</strong> {adl.identifier}</Typography><Typography><strong>Context:</strong> {adl.context}</Typography><Typography><strong>Problem:</strong> {adl.problem}</Typography><Typography><strong>Tags:</strong> {adl.tags.join(', ') || 'None'}</Typography></Stack></ContentSection><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button component={Link} to={`/adls/${adl.identifier}/adrs`}>Manage ADRs</Button>{!archived && <Button component={Link} variant="contained" to={`/adls/${adl.identifier}/adrs/new`}>Create ADR</Button>}{!archived && <Button onClick={() => navigate(`/adls/${adl.identifier}/edit`)}>Edit ADL</Button>}{!archived && <Button color="warning" onClick={() => archive.mutate()} disabled={archive.isPending}>Archive</Button>}</Stack>{archived && <Alert severity="info">This ADL is archived and read-only.</Alert>}<AuditHistory kind="adl" identifier={adl.identifier}/></Stack>;
}
